tests: shunit2: add test for _jshn_append leading space fix
Verifies the fix in commit 2065c3909935 ("libubox: Drop extraneous space
when appending values to variable") that prevents leading spaces when
appending to empty variables.

 test_jshn_append_no_leading_space
 ASSERT:expected:<foo> but was:< foo>
 ASSERT:expected:<first second> but was:< first second>

References: #16
Signed-off-by: Petr Štetiar <ynezz@true.cz>