switch from typeof to the more portable __typeof__
Depending on the existance/lack of container_of define including libubox
or uci headers (e.g. #include <uci.h>) could result in compilation
errors like:
staging_dir/target-arm_cortex-a9_musl-1.1.16_eabi/usr/include/uci.h:643:10: error: expected declaration specifiers or '...' before '(' token
   return uci_to_package(e);
staging_dir/target-arm_cortex-a9_musl-1.1.16_eabi/usr/include/uci.h:643:10: error: '__mptr' undeclared (first use in this function)
   return uci_to_package(e);

Signed-off-by: Felix Fietkau <nbd@nbd.name>
[rmilecki: add commit description]
Signed-off-by: Rafał Miłecki <rafal@milecki.pl>
(cherry picked from commit ace64897d47b9bc7af277d8a3f8a0ff67976cba8)